default:  # your profile name from dbt_project.yml
  target: dev  # your development environment
  outputs:
    
    dev:
      type: bigquery
      method: service-account
      project: ingka-fsda-devplayground-dev  # name of the project in BigQuery
      dataset: jaffle_shop  # your dataset for development (usually your name)
      threads: 4
      keyfile: /secrets/dbt-service-keyfile
      #keyfile: dbt-user-cred.json 
      timeout_seconds: 900
      priority: interactive
      retries: 1
    
    prod: # your production environment
      type: bigquery
      method: service-account
      project: ingka-fsda-devplayground-dev  # name of the project in BigQuery
      dataset: jaffle_shop  # your dataset for production
      threads: 4
      keyfile: secrets/dbt-service-keyfile
      #keyfile: dbt-user-cred.json 
      timeout_seconds: 900
      priority: interactive
      retries: 1